version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - POSTGRES_USER=AdvertisementService
      - POSTGRES_PASSWORD=zz778899
      - POSTGRES_DB=AdvertisementServiceDb
    ports:
      - 12345:8080
      - 12346:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro